# Config file for Grip Strategy Classification

# Data Parameters
data:
  raw_path: "C:/CourseWork/Classifying_grip_strategies_ml/data/02_processed/GripFormer_preprocessed_dataset.csv"

  processed_path: "C:/CourseWork/Classifying_grip_strategies_ml/data/03_processed_dl/"

# Model Parameters
model:
  num_classes: 37
  input_features: 18
  sequence_length: 512

# lstm Baseline Hyperparameter
lstm:
  hidden_size: 128
  num_layers: 2
  dropout: 0.2

# --- CNN-Transformer Hyperparameters ---
cnn_transformer:
  cnn_out_channels: 64    # Output channels of the first CNN layer
  d_model: 128            # Final dimension after CNN block, must match Transformer's d_model
  nhead: 4
  num_encoder_layers: 3
  dim_feedforward: 512
  dropout: 0.15          


# Transformer Hyperparameters 
transformer:
  d_model: 128      # Internal dimension of the model.
  nhead: 4          # Number of attention heads.
  num_encoder_layers: 3   # Number of stacked encoder layers.
  dim_feedforward: 512    # Dimension of the feed-forward network in the encoder.
  dropout: 0.1

# Training Parameters
training:
  model_to_train: "CNNTransformer"
  experiment_name: "GripTransformer"
  device: "cuda" 
  epochs: 75
  batch_size: 32
  learning_rate: 0.0001
  optimizer: "AdamW"
  schedular: "ReduceLROnPlateau"
  label_smoothing: 0.1

# Asset Paths
assets:
  scaler_path: "C:/CourseWork/Classifying_grip_strategies_ml/models/scaler.joblib"